# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "544deab1beb80bb01e5bb684a1b5fa2b"
name = "luxury-negotiation-app"
application_url = "https://nike-roland-country-maps.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-49d28a41.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nike-roland-country-maps.trycloudflare.com/auth/callback",
  "https://nike-roland-country-maps.trycloudflare.com/auth/shopify/callback",
  "https://nike-roland-country-maps.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
